// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBotjoQ3BM9PqbGZyeXutozecGI-AyoJ14',
    appId: '1:593470625300:web:442f77a6da147a0f15b901',
    messagingSenderId: '593470625300',
    projectId: 'tugasmp-a1eda',
    authDomain: 'tugasmp-a1eda.firebaseapp.com',
    storageBucket: 'tugasmp-a1eda.appspot.com',
    measurementId: 'G-D09K0HPG22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrF7dMgoOmaiyd0CjhhqMBCULWBDOHFyI',
    appId: '1:593470625300:android:5ba936317966145715b901',
    messagingSenderId: '593470625300',
    projectId: 'tugasmp-a1eda',
    storageBucket: 'tugasmp-a1eda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjB07p0DOw69OmnKCpcln5J-8zIn9TQxA',
    appId: '1:593470625300:ios:affd3820e6e4bd0e15b901',
    messagingSenderId: '593470625300',
    projectId: 'tugasmp-a1eda',
    storageBucket: 'tugasmp-a1eda.appspot.com',
    iosClientId: '593470625300-8a09503s50j49bclhl8tcrdioaoog3as.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasInputData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjB07p0DOw69OmnKCpcln5J-8zIn9TQxA',
    appId: '1:593470625300:ios:affd3820e6e4bd0e15b901',
    messagingSenderId: '593470625300',
    projectId: 'tugasmp-a1eda',
    storageBucket: 'tugasmp-a1eda.appspot.com',
    iosClientId: '593470625300-8a09503s50j49bclhl8tcrdioaoog3as.apps.googleusercontent.com',
    iosBundleId: 'com.example.tugasInputData',
  );
}
